### ISSUE TITLE
GitIgnored scenes being added to SceneGuidToPathMap json

### ISSUE THREAD

**Issue by Ale1** [starikcetin/Eflatun.SceneReference#15]
(1) Add one of your scenes to .gitignore
(2) run SceneGuitToPathMap.  the .gitignored scene will be partof the json. 
(3) howeber, other users of the repo wont have that scene in their proj (since gitignored) but it wil be listed in the map. 

there could be potential issues where users create a new asset, and it gets randomly assigned the same guid that according to the scene map is pointing to a scene, but accoriding to unity its pointing to a completely unrelated asset.

**Comment by starikcetin** [comment]
It is extremely unlikely for Unity to generate the same GUID twice, so the general consensus when working with them is to ignore that possibility altogether. GUID collisions usually happen due to user error; such as duplicating the meta files, partially reverting in version control, etc.

However, yes, we should still give an option to skip scenes ignored in version control, just to prevent irrelevant changes. I will work on this.

**Comment by starikcetin** [comment]
On second thought: instead of trying to figure out which files are ignored in version control, which would slow the editor down, would be hard to implement, and cause a lot of bloat in the package; just ignoring the map file itself in version control might be a better idea. It is a generated file after all, and will get re-generated according to the settings.

What do you think? Would that solve the issue? @Ale1

**Comment by starikcetin** [comment]
Closed with #16. 

Added a new section to README that recommends ignoring the map file, and made the generator generate a `.keep` file in the generated map folder to make sure it gets tracked by all VCS without issues. 

Will be included in the next release.

**Comment by starikcetin** [comment]
Included in [1.2.1](https://github.com/starikcetin/Eflatun.SceneReference/releases/tag/1.2.1).
