### ISSUE TITLE
Opening project with addressable + sceneReference package for first time can lead to init race condition

### ISSUE THREAD

**Issue by Ale1** [starikcetin/Eflatun.SceneReference#65]
![Screenshot 2023-08-10 at 10 18 16](https://github.com/starikcetin/Eflatun.SceneReference/assets/4612160/110c0299-f4fa-44e9-94ed-a724898f46e6)

To replicate: 

(1) check that you have  addressable package installed and enabled in your project. 
(2) close project and delete Library folder to simulate fresh install
(3) Errors above will show up, caused bye Addressable Settings being null on startup.

**Comment by Ale1** [comment]
See https://github.com/starikcetin/Eflatun.SceneReference/pull/66 for possible work-around.

**Comment by starikcetin** [comment]
This works for `AddressablesChangeListener`. However, the generator also has the same problem, but the solution there won't be as simple. I want to figure out a solution there and merge the two together with this PR.

**Comment by Selmar** [comment]
Does this cause any real problems, or is it necessary to do something to fix an issue that results from this (i.e. closing & reopening the editor)?

**Comment by starikcetin** [comment]
> Does this cause any real problems, or is it necessary to do something to fix an issue that results from this (i.e. closing & reopening the editor)? On build machines this may be important

No real issues as far as I know, it is just an annoyance. The problem stems from within the addressables package. It doesn't seem to be able to load its own settings file in time for us to use at editor startup. 

This is a tricky issue to work around because even Unity's documentation seems to be wrong (or at least inconsistent) about this behavior. 

If you encounter any critical bugs regarding this issue, please report them back.

**Comment by starikcetin** [comment]
Fixed in #87.
Included in [3.2.1](https://github.com/starikcetin/Eflatun.SceneReference/releases/tag/3.2.1).
